[dependency-groups]
dev = [
    "antiberty>=0.1.3",
    "biopython>=1.86",
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "lab>=8.8",
    "llvmlite>=0.40.0",
    "matplotlib>=3.10.8",
    "numba>=0.57.0",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "peptides>=0.5.0",
    "python-dotenv>=1.2.1",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "torch>=2.10.0",
    "transformers<4.40.0",
    "umap-learn>=0.5.11",
    "xgboost>=3.2.0",
]
